[package]
name = "shtml"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
derive_more = { version = "2.0.1", features = ["display"] }
rustyline = "16.0.0"
thiserror = "2.0.12"
