[package]
name = "shtml"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
derive_more = { version = "2.0.1", features = ["display"] }
nom = "7.1.3"
nom-span = "0.1.2"
rustyline = "16.0.0"
thiserror = "2.0.12"
